apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: advanced-aks
  name: advanced-aks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: advanced-aks
  strategy: {}
  template:
    metadata:
      labels:
        app: advanced-aks
    spec:
      containers:
        - image: advanced-aks:1.0
          name: advanced-aks
          ports:
            - containerPort: 3000
          resources: {}
status: {}
